### ISSUE TITLE
Curious why these lines are commented out

### ISSUE THREAD

**Issue by lodotek** [szinn/k8s-homelab#2911]
I see that your bootstrap kustomizations have external-secrets operator stuff commented out. Curious, why is that?
https://github.com/szinn/k8s-homelab/blob/e72079e5bf62bcda6795d25097eb57697e9492a0/kubernetes/staging/apps/kustomization.bootstrap#L12

**Comment by szinn** [comment]
WIth the file called kustomization.bootstrap, it is not part of the sync. When I start fresh, I rename to kustomization.yaml and it syncs only the uncommented entries. I repeatedly edit the file, uncomment out each remaining block one at a time, commit, and wait for the sync. When everything is done, I reset the commented out lines and rename to kustomization.bootstrap. When that is commited and resolved, the rest of the cluster is brought up.

I do this because syncing everything while cnpg and rook are coming online causes a lot of things to fail - this way, I can resolve any issues with them before everything else comes online.
